### ISSUE TITLE
Include file is not found in CMake

### ISSUE THREAD

**Issue by Rayer** [viaduck/mariadbpp#1]
Hey viaduck

Current version CMake failure due to lack of 2 files. Platform is OSX 10.13.4 with CMake 3.11.3 with CLang 9.1(It seems doesn't matter, because it fails on CMake stage)

➜  mariadbpp git:(master) cmake .
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at test/CMakeLists.txt:17 (include):
  include could not find load file:

    FindOrBuildGTest

CMake Error at CMakeLists.txt:50 (include):
  include could not find load file:

    Doxygen

-- Configuring incomplete, errors occurred!
See also "/Users/rayer/Develop/iris/deps/mariadbpp/CMakeFiles/CMakeOutput.log".

**Comment by kleest** [comment]
Did you initialize the Git submodules as stated in the [setup](https://github.com/viaduck/mariadbpp#setup) instructions?

**Comment by Rayer** [comment]
Thumbs up, thanks! Because I use it as a git submodule so I missed it should be submodule init itself, sorry for confusing~

This worked as expected now.
