### ISSUE TITLE
date_time and time don't write milliseconds

### ISSUE THREAD

**Issue by xrm** [viaduck/mariadbpp#14]
Hi there,

`src/date_time.cpp` line 501 and `src/time.cpp` line 288 should probably both read
>`    t.second_part = millisecond() * 1000;`

instead of
>`    t.second_part = 0;`

The way it's currently implemented will not send milliseconds to the sql-server.

And while I'm already here: the DateTime-object has a different implementation for some of the add_*-functions (like `add_seconds`, `add_milliseconds`, etc.) that seem to have issues with underflows (f.e. `add_milliseconds` only calls `add_seconds` when `seconds > 0`, instead of `!= 0`, as it is in the time object).

Thanks (also for fixing my last report that quick :-) ) and cheers
Sebastian

**Comment by roussosalex** [comment]
We will look into these issues for now, but in the future I think we should stay away from time and date calculations in general, instead we should switch to using C++11 `std::chrono`. Also it seems C++20 will have [calendar support](https://mariusbancila.ro/blog/2018/03/27/cpp20-calendars-and-time-zones/), which would be much easier to use than to keep fixing the date/time part of the library.

**Comment by roussosalex** [comment]
Fixed by a38874b32873109983a117862b87e3f51291ef7a.
We also added milliseconds to `time::now()` and `date_time::now()` for convenience.

**Comment by xrm** [comment]
Thanks! I'll look into using std::chrono then; I just wasn't aware that I can directly use chrono with the datetime-object before I actually checked the code. :)
