### ISSUE TITLE
Does creating a statement check for SQL injection?

### ISSUE THREAD

**Issue by HemilTheRebel** [viaduck/mariadbpp#18]

**Comment by kleest** [comment]
Prepared statements in mariadbpp use the statement API from the C client library. Therefore, binding parameters in a statement prevents an SQL injection in that parameter.  
Note, that it does not *check* for an SQL injection, but rather fails to execute the query if the parameter does not have the expected type resulting in an exception.

**Comment by HemilTheRebel** [comment]
I am content with the parameter being checked. Thanks @kleest
