### ISSUE TITLE
std::wstring support

### ISSUE THREAD

**Issue by HemilTheRebel** [viaduck/mariadbpp#20]
I am making an web service using fastcgipp. The input I get is wide character. Is there a way to use wide characters in statements? I am talking about something like:
`smt->set_wstring(0, name);`

**Comment by roussosalex** [comment]
While it is possible to set a column to `utf16` or `utf32` charset, MariaDB does [not seem to support](https://mariadb.com/kb/en/library/server-system-variables/#character_set_client) binding wide character strings: `utf16, utf32 and ucs2 cannot be used as client character sets.`

You can always use c++11 [std::codecvt](https://en.cppreference.com/w/cpp/locale/codecvt) to convert your `std::wstring` to utf8 `std::string` before binding and after querying it.

**Comment by HemilTheRebel** [comment]
Thanks
