### ISSUE TITLE
pthread is not necessary in target_link_libraries

### ISSUE THREAD

**Issue by netcho** [viaduck/mariadbpp#28]
On Windows builds, the project gets linked to pthreads, which is Unix specific. I didn't find any use in the source code. Since the project uses c++ 11 threads, this link to pthreads is not necessary.

**Comment by kleest** [comment]
C++11 provides a higher-level interface to native threading libraries. On Linux, Windows when using MinGW and macOS IIRC, you are required to link to the pthread library. I don't have experience with Visual Studio. Feel free to contribute a MR that switches linking based on compiler.
