### ISSUE TITLE
Missing include in conversion_helper.hpp

### ISSUE THREAD

**Issue by netcho** [viaduck/mariadbpp#29]
The include <stdexcept> is missing in conversion_helper.hpp which is required by the use of std::out_of_range

**Comment by kleest** [comment]
Which include do you mean? It compiles fine using GCC and clang.

**Comment by netcho** [comment]
When compiling using Visual Studio, you have to #include <stdexcept> . The whole build system assumes the library is being built under UNIX with gcc/clang
