### ISSUE TITLE
I am getting a bunch of linker errors when trying to compile

### ISSUE THREAD

**Issue by HemilTheRebel** [viaduck/mariadbpp#31]
I was successfully able to reproduce this twice on my machine. I am running fedora 30. 

This is what I did:
```bash
sudo dnf install mariadb mariadb-devel
git clone https://github.com/viaduck/mariadbpp.git
cd mariadbpp
mkdir build && cd build
cmake ../
make
```
Cmake runs perfectly fine but then make returns a bunch of linker errors. The output is too long to post. Github says the maximum permitted comment is 65536 characters. A section of the output is:
```
/usr/bin/ld: CMakeFiles/mariadbpp_tests.dir/AlterTableTest.cpp.o: in function `AlterTableTest_AlterAdd_non_existing_table_Test::TestBody()':
/home/Hemil/Downloads/github projects/mariadbpp2/test/AlterTableTest.cpp:27: undefined reference to `testing::internal::AlwaysTrue()'
/usr/bin/ld: /home/Hemil/Downloads/github projects/mariadbpp2/test/AlterTableTest.cpp:27: undefined reference to `testing::internal::AlwaysTrue()'
/usr/bin/ld: /home/Hemil/Downloads/github projects/mariadbpp2/test/AlterTableTest.cpp:27: undefined reference to `testing::Message::Message()'
/usr/bin/ld: /home/Hemil/Downloads/github projects/mariadbpp2/test/AlterTableTest.cpp:27: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
/usr/bin/ld: /home/Hemil/Downloads/github projects/mariadbpp2/test/AlterTableTest.cpp:27: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
/usr/bin/ld: /home/Hemil/Downloads/github projects/mariadbpp2/test/AlterTableTest.cpp:27: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
```

The output is filled with undefined reference to something in testing

P.S. I already have mariadbpp installed on my machine. I am trying to make a script so that others can download all the dependencies for my program automatically

**Comment by roussosalex** [comment]
Your installed googletest is likely the problem. If you don't need the tests, try turning them off via cmake `MARIADBPP_TEST=OFF` or if you do need them, clone the googletest repo and point CMake to it using `GTEST_SRC_DIR=...`

**Comment by HemilTheRebel** [comment]
I actually have gtest installed. I didn't get the logic of pointing to the source though. The solution works. Thanks

**Comment by roussosalex** [comment]
I don't know why google removed it from their FAQ, but you can still read about the issue here: [Why is it not recommended to install a pre compiled copy of googletest](https://github.com/google/googletest/blob/3847aecb5f1baca96ad974eccfc1e9ed264eec3a/googletest/docs/faq.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal)

Basically, using `GTEST_SRC_DIR` will compile gtest with the same compiler flags your tests are using, while your installed shared library might be built with different flags and cause problems.
