### ISSUE TITLE
performance -> should offer option to use mysql_use_result not only mysql_store_result

### ISSUE THREAD

**Issue by oschonrock** [viaduck/mariadbpp#33]
Title says it all really. 

Extensive StackOverflow Code review which lays bare the problem. In short:  I was struggling to beat php...and then I switched to the C-API and used mysql_use_result.

https://codereview.stackexchange.com/questions/233609/mysql-mariadb-data-extraction-string-manipulation-topn-processing-c-p

**Comment by kleest** [comment]
You can now use `mysql_use_result` by setting the following option on your connection:
```
connection->account()->set_store_result(false);
```
