### ISSUE TITLE
Formal versioning and tagging

### ISSUE THREAD

**Issue by lukem** [viaduck/mariadbpp#38]
Please consider formal versioning and tagging for mariadbpp. This would help when using own package builds of mariadbpp to identify and correlate against this upstream, besides just using the git sha1 references.

I note that the CMakeLIsts.txt has a "dummy" version of "0.0.1" for CPACK_PACKAGE_VERSION, but that's just because CPack requires a version.

**Comment by roussosalex** [comment]
We have added a tag for 1.0.0 as requested with 2562b0e0152073197cfb44c9d56d7353150fb16f.

**Comment by lukem** [comment]
Thanks!
