### ISSUE TITLE
We can neither read nor check an invalid datetime

### ISSUE THREAD

**Issue by audaki** [viaduck/mariadbpp#39]
We have a database (sadly not in our hands) which has a datetime column `value_date` which is `NOT NULL` where the value is often enough `0000-00-00 00:00:00`

Now we have a big problem with the mariadb++ library, we are completely unable to work with this column!

`res->get_string("value_date")` -> throws exception `requested type 6 does not match actual type 4type error`

`res->get_date_time("value_date")` -> throws exception `Invalid date time: 0000-00-00T00:00:00.000`

Now we tried get_is_null

`res->get_date_time("value_date")` -> returns *ALWAYS* false!

How can we work with this column?

It would be sufficient to read the value as string (we want to use std::chrono anyway) and parse it into an `std::optional<std::chrono::system_clock::time_point>`.. But right now we can do nothing and get an exception no matter what we try.

PS: get_data and get_blob fail as well.

**Comment by pirmin** [comment]
By default zero dates are allowed by MySQL. To prevent them, sql_mode must be set to a value, that includes the "NO_ZERO_DATE" option.

**Comment by audaki** [comment]
@pirmin `NO_ZERO_DATE` is only for *INSERT*ing data, but doesn't help us at all for reading zero dates with the mariadb++ library

**Comment by roussosalex** [comment]
I have looked into this and can confirm this issue. The behavior of `get_is_null` and `get_string` is expected, as `0000-00-00 00:00:00` is not null and is not internally represented as a string. I will look into fixing this by allowing all values for `get_date_time`, not just "valid" ones.

**Comment by audaki** [comment]
@roussosalex Thank you, that would be perfect!

**Comment by pirmin** [comment]
ah, ok. We're only using the mysql_real_query() and mysql_fetch_row() functions since MySQL 3, never ran into this problem

**Comment by roussosalex** [comment]
@audaki Could you try out the current master version?

**Comment by audaki** [comment]
![image](https://user-images.githubusercontent.com/1321285/87932020-1a603900-ca8b-11ea-8343-067045f4cc43.png)

![image](https://user-images.githubusercontent.com/1321285/87932035-1f24ed00-ca8b-11ea-923a-fe643181f81c.png)

Thank you, I can finally read the dates and decide what to do with them without getting an exception!

For me this issue is resolved :+1:
