### ISSUE TITLE
-Wold-style-cast warning

### ISSUE THREAD

**Issue by Pentarctagon** [viaduck/mariadbpp#40]
The use case is I was trying to include mariadbpp as a submodule in an existing project, since it isn't packaged anywhere (linux distros, vcpkg, etc), and the project has the additional warning `-Wold-style-cast`, which ends up getting triggered by the mariadbpp code.

**Comment by roussosalex** [comment]
Could you provide us with your OS and compiler versions?

**Comment by Pentarctagon** [comment]
OS is Linux Mint 20.
Compiler is `g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0`.

**Comment by Pentarctagon** [comment]
Also, a question I meant to include in the first post - would a PR to change the instances of C-style casting to C++-style casting be accepted, or would it not be?

**Comment by roussosalex** [comment]
Thanks for the offer, but we already fixed it in 114d7ea8cc871252fd6609fd12522cdcfa632f79

**Comment by Pentarctagon** [comment]
Thanks!
