### ISSUE TITLE
Make a shared library

### ISSUE THREAD

**Issue by vmartinlac** [viaduck/mariadbpp#42]
Hello,

First, thanks for your useful work on mariadbpp.
It made my life easier since I don't have to use the low-level classic mysql api or write my own wrapper.

It would be nice if there was a BUILD_SHARED cmake option allowing to build either a shared or static library.
Currently, building a shared library requires to modify the cmake listing manually.

Thanks.

**Comment by roussosalex** [comment]
Thanks! Have you tried using the cmake built-in [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html)?

**Comment by vmartinlac** [comment]
Works great thanks.
