### ISSUE TITLE
There is no way to set options

### ISSUE THREAD

**Issue by Bu11etmagnet** [viaduck/mariadbpp#5]
In `connection::connect`, there's no way to customize `m_mysql` between the call to `mysql_init` and the call to `mysql_real_connect`. This means that the library is unusable in all but the most basic scenarios (e.g. if cleartext password is needed, it can not be enabled).

**Comment by roussosalex** [comment]
I will add `account::set_connect_option` with the option to pass an arbitrary argument by value.

**Comment by roussosalex** [comment]
You can now use `account->set_connect_option(MYSQL_OPT_CONNECT_TIMEOUT, new option_arg_int(10));`.

**Comment by Bu11etmagnet** [comment]
account->set_connect_option(MYSQL_ENABLE_CLEARTEXT_PLUGIN, new mariadb::option_arg_bool{true});

worked :)
The only problem with the interface is that it's easy to do

    mariadb::option_arg_bool yes{true};
    account->set_connect_option(MYSQL_ENABLE_CLEARTEXT_PLUGIN, &yes);

which results in a segfault.

**Comment by roussosalex** [comment]
Thank you for noticing, I have improved it now. You can now do `account->set_connect_option(MYSQL_OPT_CONNECT_TIMEOUT, 10);`, which should be safe.
