### ISSUE TITLE
Does not build with MySQL Community 8.0.11

### ISSUE THREAD

**Issue by Bu11etmagnet** [viaduck/mariadbpp#6]
MySQL Community Edition doesn't have my_bool (since 8.0.1 , I think) and the struct tags are changed too.

I tried to create a PR #4 but the build fails in Travis.
What version of mysql client library is there?

**Comment by roussosalex** [comment]
Travis log says it is using `Ubuntu 14.04.5 LTS` and installing `libmariadbclient-dev` which should be version 5.5.59.

**Comment by kleest** [comment]
It is `10.0.35+maria-1~trusty`.
Excerpt from `mysql_version.h`:
```#define PROTOCOL_VERSION		10
#define MYSQL_SERVER_VERSION		"10.0.35-MariaDB"
#define MYSQL_BASE_VERSION		"mysqld-10.0"
#define MARIADB_BASE_VERSION		"mariadb-10.0"
#define MYSQL_SERVER_SUFFIX_DEF		"-1~trusty"
#define FRM_VER				6
#define MYSQL_VERSION_ID		100035
```
This means, your condition `#if MYSQL_VERSION_ID < 80000 ` evaluates to `true` for every MariaDB version >= 10, thus breaking the build.

**Comment by Bu11etmagnet** [comment]
```
MYSQL_VERSION_ID		100035
```
Ouch. I didn't expect that.
