### ISSUE TITLE
MariaDB Connector-C: Missing mysql_version.h

### ISSUE THREAD

**Issue by kleest** [viaduck/mariadbpp#8]
As reported by @joaquin-herrero, the [MariaDB Connector-C](https://github.com/MariaDB/mariadb-connector-c) does not provide the `mysql_version.h` header but uses the file `mariadb_version.h` instead.

7db2285d1c6ffe02f3e2ffa2bfb1f91fa0cf04d5 fails building with MariaDB Connector-C.

**Comment by kleest** [comment]
`mysql_version.h` -> `mariadb_version.h` rename introduced in https://github.com/MariaDB/mariadb-connector-c/commit/4ca933bb817efd90076d5bde968761047ac7e4cf#diff-6005b12e9a4ecd5532b0a3f629c5a4e6.

**Comment by kleest** [comment]
@joaquin-herrero could you test the latest master?

**Comment by joaquin-herrero** [comment]
@kleest yes, it works now! Thanks for your quick fix :)
